services:
  - type: web
    name: project-management
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project_management.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project_management.settings
      - key: SECRET_KEY
        value: DJANGO_SECRET_KEY
      - key: DEBUG
        value: 'False'
